{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mysql-chart.fullname" . }}
  labels:
    {{- include "mysql-chart.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
