name = "servv-support-worker"
main = "servv-support-demo/worker.js"
compatibility_date = "2025-09-17"

account_id = "28eb76f22b8fa45bb00e1e8196f8cd89"

kv_namespaces = [
  { binding = "SERVV_SUBMISSIONS", id = "ca0a6fda2805484fbb8dce7eb0f8167f" }
]
