# Number of WordPress replicas
replicaCount: 1

# WordPress image details
image:
  repository: wordpress
  tag: latest
  pullPolicy: IfNotPresent

# WordPress container environment variables
env:
  WORDPRESS_DB_HOST: mysql-release-mysql.default.svc.cluster.local
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: wordpresspassword
  WORDPRESS_DB_NAME: wordpress


# Kubernetes Service for WordPress
service:
  type: NodePort   # Expose service outside Minikube
  port: 80

serviceAccount:
  create: true
  name: "wordpress-sa"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# MySQL Configuration
mysql:
  enabled: true
  image:
    repository: mysql
    tag: "5.7"
  service:
    type: ClusterIP
  env:
    MYSQL_ROOT_PASSWORD: "password"
    MYSQL_DATABASE: "wordpress"

# Resource limits (optional)
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Node selector, tolerations, affinity (optional, can be empty for now)
nodeSelector: {}
tolerations: []
affinity: {}
