name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
env:
   ACR_NAME: temprgacr
   IMAGE_NAME: wpcustom
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'   
          allow-no-subscriptions: true
      - name: Login to ACR
        run: az acr login --name $ACR_NAME
 
    - name: Build Docker Image
      run: |
        docker build -t $ACR_NAME.azurecr.io/my-wordpress:latest .

    - name: Push Docker image to ACR
      run: |
        docker push $ACR_NAME.azurecr.io/my-wordpress:latest

